Pm 865cu6ayy bsky regex validation
devdotxyz/eth-xyz pull request #129
Opened 2023-07-26 23:52 UTC by makhnovskiy

2023-07-27 15:18 UTC, TonnyORG commented
@makhnovskiy pls resolve conflicts

2023-07-27 15:18 UTC, TonnyORG requested changes
@makhnovskiy Please resolve conflicts

2023-07-27 21:28 UTC, TonnyORG requested changes

2023-07-27 21:28 UTC, TonnyORG commented on services/EnsService.ts
> +    if(!record.match(/^did=did:plc:[0-9a-zA-Z]+$/) || record.length !== 36) {
@makhnovskiy you can add `{24}` instead of the `+` to your regex and it would validate the exact length as well:
`/^did=did:plc:[0-9a-zA-Z]{24}$/`

2023-07-27 22:06 UTC, makhnovskiy commented
@TonnyORG Changes completed

2023-07-28 15:19 UTC, TonnyORG approved these changes

2023-07-28 15:19 UTC, merged