Pm 8678gjzxn custom text records
devdotxyz/eth-xyz pull request #153
Opened 2023-09-29 16:15 UTC by makhnovskiy

2023-09-29 20:27 UTC, brendandebeasi approved these changes

2023-09-29 20:29 UTC, brendandebeasi commented
@makhnovskiy Can you resolve the conflicts from the other two merges please?

2023-10-02 16:06 UTC, TonnyORG requested changes

2023-10-02 18:13 UTC, TonnyORG approved these changes

2023-10-02 18:13 UTC, merged